baseURL: http://www.infoaux.am/
languageCode: en-us
title: InfoAux | Managed IT services masters
#theme: hugo-fresh
module:
  imports:
    path: hugo-fresh
#googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: false
  # Used as meta data; describe your site to make Google Bots happy
  description: InfoAux LLC website
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: /logos/infoAuxlogo.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  navbar:
  - title: About
    url: /
#  - title: Pricing
#    url: /
  - title: Services
    sublinks:
    - title: Backup as a Service
      url: /services/baas
    - title: Disaster recovery as a Service
      url: /services/draas
    - title: Technical Support
      url: /services/support
 # - title: Log in
 #   url: /
  - title: Log in
    url: /
    button: true
 # sidebar:
 #   # Logo (from /images/logos/___.svg)
 #   logo: fresh-square
 #   sections:
 #   - title: User
 #     icon: user
 #     links:
 #     - text: Profile
 #       url: /
 #     - text: Account
 #       url: /
 #     - text: Settings
 #       url: /
 #   - title: Messages
 #     icon: envelope
 #     links:
 #     - text: Inbox
 #       url: /
 #     - text: Compose
 #       url: /
 #   - title: Images
 #     icon: image
 #     links:
 #     - text: Library
 #       url: /
 #     - text: Upload
 #       url: /
 #   - title: Settings
 #     icon: cog
 #     links:
 #     - text: User settings
 #       url: /
 #     - text: App settings
 #       url: /
  ###
  ### MAIN BODY
  ###
  hero:
    # Main hero title
    title: Managed Data Protection Services
    # Hero subtitle (optional)
    subtitle: "We simplify and accelerate the design, build and deployment of Data Protection. 
    We help customers find the right solution to meet their objectives and provide expert advice to successfully launch services."
    # Button text
    buttontext: Contact us
    # Where the main hero button links to
    buttonlink: "services/"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
#    clientlogos:
#    - systek
#    - tribe
#    - kromo
#    - infinite
#    - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  section1:
    title: Our Solutions offering
    subtitle: Data is the fundamental backbone of every company
    tiles:
    - title: Backup as a Service
      icon: mouse-globe
      text: Protect your mission-critical data
      url: /services/baas
      buttonText: BaaS
    - title: Disaster Recovery
      icon: laptop-cloud
      text: DR services ensure your data is recovered quickly
      url: /services/draas
      buttonText: DRaaS
    - title: Technical Support
      icon: plug-cloud
      text: Maintaining service quality to our customers
      url: /services/support
      buttonText: Support
  section2:
    title: Our approach
    subtitle: Managed IT services masters
    features:
    - title: We understand that all businesses have different data requirements
      text: We take care of your data protection needs, finding modern and adaptable ways to keep your data secure, ensuring continuous access to your data.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Leading technology in place
      text: Ability to design, build and operate complex technical solutions allows our customers to focus on the elements that really add value to their business.
      icon: doc-sync
    - title: Proven experts team
      text: Fully managed combination of consulting, operations and techincal support to provide an end to end experience. Proven experts team and approach giving you a trusted partner for day to day support of your environment
      icon: mobile-feed
#  section3:
#    title: One platform
#    subtitle: To rule them all
#    image: illustrations/mockups/app-mockup.png
#    buttonText: Get started
#    buttonLink: "#"
#  section4:
#    title: Our Clients love us!
#    subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
#    clients:
#    - name: Irma Walters
#      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
#      job: Accountant
#      img: 1
#    - name: John Bradley
#      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
#      job: Financial Analyst
#      img: 2
#    - name: Gary Blackman
#      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
#      job: HR Manager
#      img: 3
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: infoAuxlogo.svg
    # Social Media Title
#    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
#    socialmedia:
#    - link: https://github.com/lucperkins/github-fresh
      # Icons are from Font Awesome
 #     icon: github
 #   - link: https://dribbble.com/#
 #     icon: dribbble
 #   - link: https://facebook.com/#
 #     icon: facebook
 #   - link: https://twitter.com/lucperkins
 #     icon: twitter
 #   - link: https://bitbucket.org/#
 #     icon: bitbucket
    bulmalogo: false
    quicklinks:
      column1:
        title: "Services"
        links:
        - text: Backup
          link: /services/baas
        - text: DR
          link: /services/draas
        - text: Support
          link: /services/support
      column2:
        title: ""
        links:
        - text: 
          link: /
#        - text: User guides
#          link: /
#        - text: Admin guide
#          link: /
#        - text: Developers
#          link: /
      column3:
        title: ""
        links:
        - text: 
          link: /

